# Generated by Django 4.2.30 on 2026-06-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_ascii_slugs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicefield',
            name='unique_service_field_name',
        ),
        migrations.AlterUniqueTogether(
            name='servicefield',
            unique_together={('service', 'field_name')},
        ),
    ]
