# Generated by Django 4.2.30 on 2026-06-17 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقا ۱۰ رقم باشد.', regex='^[0-9]{10}$')], verbose_name='کد ملی'),
        ),
    ]
