# Generated by Django 4.2.30 on 2026-06-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycsitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل احراز هویت', 'verbose_name_plural': 'پروفایل\u200cهای احراز هویت'},
        ),
        migrations.AlterModelOptions(
            name='kycsitesettings',
            options={'verbose_name': 'تنظیمات احراز هویت', 'verbose_name_plural': 'تنظیمات احراز هویت'},
        ),
    ]
