# Generated by Django 4.2.30 on 2026-06-18 04:36

from django.db import migrations, models


def mark_customer_messages_read(apps, schema_editor):
    OrderMessage = apps.get_model('orders', 'OrderMessage')
    OrderMessage.objects.filter(sender__is_staff=False).update(is_read=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordercounter_private_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.RunPython(
            mark_customer_messages_read,
            migrations.RunPython.noop,
        ),
    ]
