# Generated by Django 4.2.30 on 2026-06-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'تاریخچه وضعیت', 'verbose_name_plural': 'تاریخچه وضعیت\u200cها'},
        ),
    ]
